name: no_sheet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^8.0.0
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  # Utilities
  intl: ^0.20.0
  uuid: ^4.0.0
  connectivity_plus: ^6.0.0
  pdf: ^3.0.0
  printing: ^5.0.0
  # UI components
  image_picker: ^1.0.0
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.0
  flutter_svg: ^2.0.0
  url_launcher: ^6.0.0
  fl_chart: ^1.0.0
  google_fonts: ^6.0.0
  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded constraint as suggested
  mockito: ^5.4.0 # No newer major version suggested
  build_runner: ^2.0.0 # No newer major version suggested
  hive_generator: ^2.0.0 # No newer major version suggested

flutter:
  uses-material-design: true
