name: no_sheet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'  # Changed to range format

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages (properly indented)
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  # Utilities
  intl: ^0.18.1
  uuid: ^3.0.7
  connectivity_plus: ^4.0.2
  pdf: ^3.10.4
  printing: ^5.11.0
  # UI components
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Kept the newer version
  mockito: ^5.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg