name: no_sheet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_auth_web: ^5.0.0
  firebase_messaging: ^15.0.0
  firebase_messaging_web: ^3.0.0
  firebase_storage: ^12.0.0
  firebase_storage_web: ^3.0.0
  cloud_firestore: ^5.0.0
  # State management
  flutter_bloc: ^9.0.0 # Relaxed constraint
  equatable: ^2.0.5 # No newer major version suggested, keep as is or check for minor updates if needed
  get_it: ^8.0.0 # Relaxed constraint
  # Local storage
  hive: ^2.2.3 # No newer major version suggested
  hive_flutter: ^1.1.0 # No newer major version suggested
  path_provider: ^2.1.0 # No newer major version suggested
  # Utilities
  intl: ^0.20.0 # Relaxed constraint
  uuid: ^4.0.0 # Relaxed constraint
  connectivity_plus: ^6.0.0 # Relaxed constraint
  pdf: ^3.0.0 # No newer major version suggested
  printing: ^5.0.0 # No newer major version suggested
  # UI components
  image_picker: ^1.0.0 # No newer major version suggested
  cached_network_image: ^3.0.0 # Relaxed constraint
  shared_preferences: ^2.0.0 # No newer major version suggested
  flutter_svg: ^2.0.0 # No newer major version suggested
  url_launcher: ^6.0.0 # No newer major version suggested
  fl_chart: ^1.0.0 # Relaxed constraint
  google_fonts: ^6.0.0 # Relaxed constraint
  # iOS style icons
  cupertino_icons: ^1.0.8 # No newer major version suggested

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Downgraded constraint as suggested
  mockito: ^5.4.0 # No newer major version suggested
  build_runner: ^2.0.0 # No newer major version suggested
  hive_generator: ^2.0.0 # No newer major version suggested

flutter:
  uses-material-design: true
