// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXyHgskXYcWII9TGptKNs4CD3HFJHONns',
    appId: '1:458115766413:web:f68212e444c0dec46b2ac4',
    messagingSenderId: '458115766413',
    projectId: 'nosheet-fabbd',
    authDomain: 'nosheet-fabbd.firebaseapp.com',
    storageBucket: 'nosheet-fabbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7jWBt7WLBqVF-OEX6554d-Xh_enkndM',
    appId: '1:458115766413:android:8b8ad6ec4843356d6b2ac4',
    messagingSenderId: '458115766413',
    projectId: 'nosheet-fabbd',
    storageBucket: 'nosheet-fabbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhMCrT6FELb9nj5oZ2i_OwLgM0bEpmsNw',
    appId: '1:458115766413:ios:68d285246915bace6b2ac4',
    messagingSenderId: '458115766413',
    projectId: 'nosheet-fabbd',
    storageBucket: 'nosheet-fabbd.firebasestorage.app',
    iosBundleId: 'com.example.noSheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhMCrT6FELb9nj5oZ2i_OwLgM0bEpmsNw',
    appId: '1:458115766413:ios:68d285246915bace6b2ac4',
    messagingSenderId: '458115766413',
    projectId: 'nosheet-fabbd',
    storageBucket: 'nosheet-fabbd.firebasestorage.app',
    iosBundleId: 'com.example.noSheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXyHgskXYcWII9TGptKNs4CD3HFJHONns',
    appId: '1:458115766413:web:446ebe257eb0c1bd6b2ac4',
    messagingSenderId: '458115766413',
    projectId: 'nosheet-fabbd',
    authDomain: 'nosheet-fabbd.firebaseapp.com',
    storageBucket: 'nosheet-fabbd.firebasestorage.app',
  );
}
