// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'app.dart';

void main() async {
  // Ensure that the Flutter binding is initialized before initializing Firebase.
  // This is required for Firebase to function correctly within the Flutter application lifecycle.
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initialize Firebase for the current platform.
    // DefaultFirebaseOptions is generated by the FlutterFire CLI and contains
    // the configuration for your Firebase project for each platform (iOS, Android, Web, etc.).
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // Print a success message if Firebase initializes correctly.
    print('Firebase initialized successfully');
  } catch (e) {
    // Print an error message if Firebase initialization fails.
    print('Failed to initialize Firebase: $e');
  }

  runApp(const NoSheetApp());
}